#!/bin/bash

# Script to add override keywords to methods that need them

# Function to add override to a specific method in a file
add_override() {
    local file="$1"
    local method_pattern="$2"
    
    if [ -f "$file" ]; then
        # Use sed to add 'override ' before the method definition
        sed -i '' "s/    def ${method_pattern}/    override def ${method_pattern}/g" "$file"
        echo "Updated $file"
    fi
}

# Add override to render methods
echo "Adding override to render methods..."
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsAnimatedImageAnimatedImageMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsAnimationAnimationMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsAvatarAvatarMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsBadgeBadgeMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsBreadcrumbBreadcrumbMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsButtonButtonMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsButtonGroupButtonGroupMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsCalloutCalloutMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsCardCardMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsCarouselCarouselMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsCarouselItemCarouselItemMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsCheckboxCheckboxMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsColorPickerColorPickerMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsComparisonComparisonMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsCopyButtonCopyButtonMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsDetailsDetailsMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsDialogDialogMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsDrawerDrawerMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsDropdownDropdownMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsDropdownItemDropdownItemMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsIncludeIncludeMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsInputInputMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsMutationObserverMutationObserverMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsOptionOptionMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsPagePageMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsPopoverPopoverMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsPopupPopupMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsProgressBarProgressBarMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsProgressRingProgressRingMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsQrCodeQrCodeMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsRadioRadioMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsRadioGroupRadioGroupMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsRatingRatingMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsRelativeTimeRelativeTimeMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsResizeObserverResizeObserverMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsScrollerScrollerMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsSelectSelectMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsSkeletonSkeletonMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsSliderSliderMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsSpinnerSpinnerMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsSplitPanelSplitPanelMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsSwitchSwitchMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTabGroupTabGroupMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTabPanelTabPanelMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTabTabMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTagTagMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTextareaTextareaMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTooltipTooltipMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTreeItemTreeItemMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTreeTreeMod.scala" "render():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsZoomableFrameZoomableFrameMod.scala" "render():"

# Add override to focus methods
echo "Adding override to focus methods..."
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsButtonButtonMod.scala" "focus():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsButtonButtonMod.scala" "focus(options:"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsCheckboxCheckboxMod.scala" "focus():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsCheckboxCheckboxMod.scala" "focus(options:"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsColorPickerColorPickerMod.scala" "focus():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsColorPickerColorPickerMod.scala" "focus(options:"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsInputInputMod.scala" "focus():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsInputInputMod.scala" "focus(options:"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsRadioGroupRadioGroupMod.scala" "focus():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsRadioGroupRadioGroupMod.scala" "focus(options:"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsRatingRatingMod.scala" "focus():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsRatingRatingMod.scala" "focus(options:"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsSelectSelectMod.scala" "focus():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsSelectSelectMod.scala" "focus(options:"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsSliderSliderMod.scala" "focus():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsSwitchSwitchMod.scala" "focus():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsSwitchSwitchMod.scala" "focus(options:"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTextareaTextareaMod.scala" "focus():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTextareaTextareaMod.scala" "focus(options:"

# Add override to connectedCallback methods
echo "Adding override to connectedCallback methods..."
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsAnimationAnimationMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsCarouselCarouselMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsCarouselItemCarouselItemMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsDividerDividerMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsDropdownItemDropdownItemMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsIconIconMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsMutationObserverMutationObserverMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsOptionOptionMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsPagePageMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsPopoverPopoverMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsPopupPopupMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsResizeObserverResizeObserverMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsScrollerScrollerMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsSplitPanelSplitPanelMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTabGroupTabGroupMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTabPanelTabPanelMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTabTabMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTooltipTooltipMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTreeItemTreeItemMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTreeTreeMod.scala" "connectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distInternalWebawesomeFormAssociatedElementMod.scala" "connectedCallback():"

# Add override to disconnectedCallback methods
echo "Adding override to disconnectedCallback methods..."
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsAnimationAnimationMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsCarouselCarouselMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsDetailsDetailsMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsDialogDialogMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsDrawerDrawerMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsDropdownDropdownMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsDropdownItemDropdownItemMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsIconIconMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsMutationObserverMutationObserverMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsOptionOptionMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsPagePageMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsPopoverPopoverMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsPopupPopupMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsRelativeTimeRelativeTimeMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsResizeObserverResizeObserverMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsScrollerScrollerMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsSplitPanelSplitPanelMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTabGroupTabGroupMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTextareaTextareaMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTooltipTooltipMod.scala" "disconnectedCallback():"
add_override "webawesome/src/io/github/nguyenyou/webawesome/awesomeMeWebawesome/distComponentsTreeTreeMod.scala" "disconnectedCallback():"

echo "Script completed!"