name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
jobs:
  publish-artifacts:
    runs-on: ubuntu-latest
    env:
      MILL_SONATYPE_USERNAME: ${{ secrets.MILL_SONATYPE_USERNAME }}
      MILL_SONATYPE_PASSWORD: ${{ secrets.MILL_SONATYPE_PASSWORD }}
      MILL_PGP_SECRET_BASE64: ${{ secrets.MILL_PGP_SECRET_BASE64 }}
      MILL_PGP_PASSPHRASE: ${{ secrets.MILL_PGP_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
      - run: ./mill -i webawesome-laminar.publishSonatypeCentral
